version: '3.9'

services:
  mqtt-broker:
    image: eclipse-mosquitto:latest
    container_name: mqtt_broker
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - botnet-network

  node-server:
    build:
      context: ./node-server
    container_name: node-server
    depends_on:
      - mqtt-broker
    networks:
      - botnet-network
    ports:
      - "3000:3000"
    environment:
      MQTT_BROKER_HOST: mqtt-broker
      MQTT_PORT: 1883

  device_1:
    build:
      context: ./device
    container_name: device_1
    depends_on:
      - mqtt-broker
    networks:
      - botnet-network
    environment:
      MQTT_BROKER_HOST: mqtt-broker
      MQTT_PORT: 1883
      
  device_2:
    build:
      context: ./device
    container_name: device_2
    depends_on:
      - mqtt-broker
    networks:
      - botnet-network
    environment:
      MQTT_BROKER_HOST: mqtt-broker
      MQTT_PORT: 1883

networks:
  botnet-network:
    driver: bridge
