version: '3.9'

services:
  mqtt-broker:
    image: eclipse-mosquitto:latest
    container_name: mqtt_broker
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - botnet-network

  node-control:
    build:
      context: ./node-control
    container_name: node-control
    depends_on:
      - mqtt-broker
    networks:
      - botnet-network
    ports:
      - "3000:3000"
    environment:
      MQTT_BROKER_HOST: mqtt-broker
      MQTT_PORT: 1883

  device_1:
    build:
      context: ./device
    container_name: device_1
    depends_on:
      - mqtt-broker
    networks:
      - botnet-network
    environment:
      MQTT_BROKER_HOST: mqtt-broker
      MQTT_PORT: 1883
      
  device_2:
    build:
      context: ./device
    container_name: device_2
    depends_on:
      - mqtt-broker
    environment:
      MQTT_BROKER_HOST: mqtt-broker
      MQTT_PORT: 1883
    networks:
      - botnet-network

  device_3:
    build:
      context: ./device
    container_name: device_3
    depends_on:
      - mqtt-broker
    environment:
      MQTT_BROKER_HOST: mqtt-broker
      MQTT_PORT: 1883
    networks:
      - botnet-network

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d/meta.conf:/etc/nginx/conf.d/meta.conf
    networks:
      - botnet-network

  node-meta-1:
    build:
      context: ./node-meta
    container_name: node-meta-1
    environment:
      - PORT=4000
      - SERVER_NAME=meta-server-1
      - MAX_REQUESTS_LIMIT=50
    networks:
      - botnet-network

  node-meta-2:
    build:
      context: ./node-meta
    container_name: node-meta-2
    environment:
      - PORT=5000
      - SERVER_NAME=meta-server-2
      - MAX_REQUESTS_LIMIT=50
    networks:
      - botnet-network

  node-meta-3:
    build:
      context: ./node-meta
    container_name: node-meta-3
    environment:
      - PORT=6000
      - SERVER_NAME=meta-server-3
      - MAX_REQUESTS_LIMIT=50
    networks:
      - botnet-network

networks:
  botnet-network:
    driver: bridge
